sudo: required

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pnew_password
  - sudo service mysql restart
  - sudo mysql -u root -pnew_password -e "SET GLOBAL sql_mode = '';"

cache:
  directories:
    - $HOME/.cache

before_cache:
  - sudo chown -R travis:travis $HOME/.cache

services:
  - docker

before_script:
  - docker-compose -f docker-compose.travis.yml up -d --build

script:
  - scripts/travis.sh

after_script:
  - docker-compose -f docker-compose.travis.yml down

deploy:
  provider: script
  script: make deploy-photoprism deploy-demo
  skip_cleanup: true
  on:
    branch: master